### ISSUE TITLE
AttributeError: 'LlavaNextProcessor' object has no attribute 'process'

### ISSUE THREAD

**Issue by jrp2014** [Blaizzy/mlx-vlm#120]
Llava and various other models seem to have been broken recently.  Or is it just me?

```bash
> python mytest.py
Model:  mlx-community/llava-v1.6-mistral-7b-8bit
Fetching 12 files: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 12/12 [00:00<00:00, 50483.10it/s]
Fetching 12 files: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 12/12 [00:00<00:00, 65536.00it/s]
Image:  20241109-183008_L1010445_DxO.jpg
==========
Image: /Users/xxx/Pictures/Processed/20241109-183008_L1010445_DxO.jpg 

Prompt: [INST] <image>
Provide a factual caption, description and comma-separated keywords or tags for this image so that it can be searched for easily [/INST]
Traceback (most recent call last):
  File "/Users/xxx/Documents/AI/mlx/scripts/vlm/mytest.py", line 36, in <module>
    output = generate(model, processor, pic, formatted_prompt, max_tokens=500, verbose=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/mlx/lib/python3.12/site-packages/mlx_vlm/utils.py", line 1148, in generate
    inputs = prepare_inputs(
             ^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/mlx/lib/python3.12/site-packages/mlx_vlm/utils.py", line 865, in prepare_inputs
    inputs = processor.process(
             ^^^^^^^^^^^^^^^^^
AttributeError: 'LlavaNextProcessor' object has no attribute 'process'
```

**Comment by Blaizzy** [comment]
Please install from source and let me know if the issue persists.

**Comment by jrp2014** [comment]
Yes, that was installed from source. (`pip install .`)

The only remotely interesting thing I see is

```
 /opt/homebrew/Caskroom/miniconda/base/envs/mlx/lib/python3.12/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
  !!

          ********************************************************************************
          Please avoid running ``setup.py`` directly.
          Instead, use pypa/build, pypa/installer or other
          standards-based tools.

          See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
          ********************************************************************************

  !!
```

**Comment by jrp2014** [comment]
Just pulled again and we seem to be back to normal.

**Comment by Blaizzy** [comment]
Awesome! 

Sorry for that,

Molmo PR introduced a bug 🐛 because it's not in HF format but I fixed it with the Florence-2 PR.

I will put some guardrails over the weekend to avoid this in the future.
