### ISSUE TITLE
SmolVLM-Instruct-8bit tokenizer error

### ISSUE THREAD

**Issue by abaranovskis-redsamurai** [Blaizzy/mlx-vlm#139]
Hi,

Getting this error, when running `python -m mlx_vlm.generate --model mlx-community/SmolVLM-Instruct-8bit --max-tokens 100 --temp 0.0`:

```
Prompt: <|im_start|><|start_header_id|>user<|end_header_id|>

[{'type': 'image'}, {'type': 'text', 'text': 'What are these?'}]<|eot_id|><|start_header_id|>assistant<|end_header_id|>


Traceback (most recent call last):
  File "/.pyenv/versions/3.10.4/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/.pyenv/versions/3.10.4/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/lib/python3.10/site-packages/mlx_vlm/generate.py", line 111, in <module>
    main()
  File "/lib/python3.10/site-packages/mlx_vlm/generate.py", line 95, in main
    output = generate(
  File "/lib/python3.10/site-packages/mlx_vlm/utils.py", line 1181, in generate
    prompt_tokens = mx.array(processor.tokenizer.encode(prompt))
AttributeError: 'GPT2TokenizerFast' object has no attribute 'tokenizer'. Did you mean: '_tokenizer'?
```

mlx-vlm = 0.1.3
mlx = 0.21.0

**Comment by Blaizzy** [comment]
Hey @abaranovskis-redsamurai 

Please upgrade your transformers, try again and let me know if the issue persists

**Comment by abaranovskis-redsamurai** [comment]
This works, thanks!

**Comment by Blaizzy** [comment]
My pleasure!😊

**Comment by samrat** [comment]
Hello @Blaizzy 👋 ,

I am still getting this error with `transformers 4.49.0`

```
❯ pip install 'transformers>=4.49.0'

❯ python -m mlx_vlm.generate \
  --model mlx-community/SmolVLM2-500M-Video-Instruct-mlx \
  --image https://huggingface.co/datasets/huggingface/documentation-images/resolve/main/bee.jpg \
  --prompt "Can you describe this image?"
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
This is a beta version of the video understanding. It may not work as expected.
Fetching 12 files: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 12/12 [00:00<00:00, 136400.13it/s]
==========
Files: ['https://huggingface.co/datasets/huggingface/documentation-images/resolve/main/bee.jpg']

Prompt: <|im_start|>User:<image>Can you describe this image?<end_of_utterance>
Assistant:
Traceback (most recent call last):
  File "/Users/samrat/mambaforge/envs/mlx-env/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/samrat/mambaforge/envs/mlx-env/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/samrat/mambaforge/envs/mlx-env/lib/python3.10/site-packages/mlx_vlm/generate.py", line 156, in <module>
    main()
  File "/Users/samrat/mambaforge/envs/mlx-env/lib/python3.10/site-packages/mlx_vlm/generate.py", line 141, in main
    output = generate(
  File "/Users/samrat/mambaforge/envs/mlx-env/lib/python3.10/site-packages/mlx_vlm/utils.py", line 1115, in generate
    for response in stream_generate(model, processor, prompt, image, **kwargs):
  File "/Users/samrat/mambaforge/envs/mlx-env/lib/python3.10/site-packages/mlx_vlm/utils.py", line 1016, in stream_generate
    inputs = prepare_inputs(
  File "/Users/samrat/mambaforge/envs/mlx-env/lib/python3.10/site-packages/mlx_vlm/utils.py", line 806, in prepare_inputs
    processor.tokenizer.pad_token = processor.tokenizer.eos_token
  File "/Users/samrat/mambaforge/envs/mlx-env/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 1108, in __getattr__
    raise AttributeError(f"{self.__class__.__name__} has no attribute {key}")
AttributeError: GPT2TokenizerFast has no attribute tokenizer. Did you mean: '_tokenizer'?
```

**Comment by Blaizzy** [comment]
@pcuenca did you encounter this issue?

**Comment by pcuenca** [comment]
Hi @samrat, for SmolVLM2 you need to install transformers from `main`, or from this stable branch:

```
pip install git+https://github.com/huggingface/transformers@v4.49.0-SmolVLM2
```

transformers 4.49.0 was released yesterday and smolvlm2 today, so it'll take a few weeks to have it in 4.50. But the branch above is stable 🤗

**Comment by samrat** [comment]
@pcuenca Thank you, that worked! Though the branch seems to be called `v4.49.0-SmolVLM-2-release`: https://github.com/huggingface/transformers/tree/v4.49.0-SmolVLM-2-release

**Comment by pcuenca** [comment]
Ah! It's a tag but there was a typo in the tag name (should have been `v4.49.0-SmolVLM-2` not `v4.49.0-SmolVLM2`, fixed). Both the tag and the branch should work now! Sorry, and thanks 🤗
