### ISSUE TITLE
Latest mlx seems to break mlx-vlm + Qwen2

### ISSUE THREAD

**Issue by jrp2014** [Blaizzy/mlx-vlm#154]
```
> python -m mlx_vlm.generate --model mlx-community/Qwen2-VL-7B-Instruct-8bit --max-tokens 100 --temp 0.0

added_tokens.json: 100%|███████████████████████████████████████████████████████████████| 392/392 [00:00<00:00, 327kB/s]
chat_template.json: 100%|█████████████████████████████████████████████████████████| 1.05k/1.05k [00:00<00:00, 1.07MB/s]
config.json: 100%|████████████████████████████████████████████████████████████████| 1.41k/1.41k [00:00<00:00, 1.03MB/s]
preprocessor_config.json: 100%|███████████████████████████████████████████████████████| 567/567 [00:00<00:00, 1.05MB/s]
model.safetensors.index.json: 100%|█████████████████████████████████████████████████| 129k/129k [00:00<00:00, 1.64MB/s]
tokenizer_config.json: 100%|██████████████████████████████████████████████████████| 4.30k/4.30k [00:00<00:00, 1.62MB/s]
special_tokens_map.json: 100%|████████████████████████████████████████████████████████| 613/613 [00:00<00:00, 3.88MB/s]
merges.txt: 100%|█████████████████████████████████████████████████████████████████| 1.67M/1.67M [00:00<00:00, 3.04MB/s]
vocab.json: 100%|█████████████████████████████████████████████████████████████████| 2.78M/2.78M [00:01<00:00, 2.00MB/s]
tokenizer.json: 100%|█████████████████████████████████████████████████████████████| 11.4M/11.4M [00:01<00:00, 7.51MB/s]
model-00002-of-00002.safetensors: 100%|███████████████████████████████████████████| 3.45G/3.45G [03:50<00:00, 15.0MB/s]
model-00001-of-00002.safetensors: 100%|███████████████████████████████████████████| 5.36G/5.36G [05:04<00:00, 17.6MB/s]
Fetching 12 files: 100%|███████████████████████████████████████████████████████████████| 12/12 [05:04<00:00, 25.39s/it]
==========1-of-00002.safetensors:  60%|█████████████████████████▉                 | 3.24G/5.36G [03:50<02:34, 13.8MB/s]
Image: ['http://images.cocodataset.org/val2017/000000039769.jpg'] ████████████████| 5.36G/5.36G [05:04<00:00, 28.5MB/s]

Prompt: <|im_start|>system
You are a helpful assistant.<|im_end|>
<|im_start|>user
What are these?<|vision_start|><|image_pad|><|vision_end|><|im_end|>
<|im_start|>assistant

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/opt/homebrew/Caskroom/miniconda/base/envs/mlx/lib/python3.12/site-packages/mlx_vlm/generate.py", line 111, in <module>
    main()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/mlx/lib/python3.12/site-packages/mlx_vlm/generate.py", line 95, in main
    output = generate(
             ^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/mlx/lib/python3.12/site-packages/mlx_vlm/utils.py", line 1229, in generate
    for (token, prob), n in zip(generator, range(max_tokens)):
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/mlx/lib/python3.12/site-packages/mlx_vlm/utils.py", line 1039, in generate_step
    outputs = model(input_ids, pixel_values, cache=cache, mask=mask, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/mlx/lib/python3.12/site-packages/mlx_vlm/models/qwen2_vl/qwen2_vl.py", line 99, in __call__
    input_embddings = self.get_input_embeddings(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/mlx/lib/python3.12/site-packages/mlx_vlm/models/qwen2_vl/qwen2_vl.py", line 60, in get_input_embeddings
    hidden_states = self.vision_tower(
                    ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/mlx/lib/python3.12/site-packages/mlx_vlm/models/qwen2_vl/vision.py", line 292, in __call__
    rotary_pos_emb = self.rot_pos_emb(grid_thw)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/mlx/lib/python3.12/site-packages/mlx_vlm/models/qwen2_vl/vision.py", line 278, in rot_pos_emb
    rotary_pos_emb_full = self.rotary_pos_emb(max_grid_size)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/mlx/lib/python3.12/site-packages/mlx_vlm/models/qwen2_vl/vision.py", line 91, in __call__
    seq = mx.arange(seqlen, dtype=inv_freq.dtype)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: arange(): incompatible function arguments. The following argument types are supported:
    1. arange(start : Union[int, float], stop : Union[int, float], step : Union[None, int, float], dtype: Optional[Dtype] = None, *, stream: Union[None, Stream, Device] = None) -> array
    2. arange(stop : Union[int, float], step : Union[None, int, float] = None, dtype: Optional[Dtype] = None, *, stream: Union[None, Stream, Device] = None) -> array

```

**Comment by Blaizzy** [comment]
Thank you very much @jrp2014!

Your issues have been invaluable to me and the community.

I'm replicating it to see what happend and will fix any issues ASAP.

**Comment by jrp2014** [comment]
You are welcome.  If you have a preferred test script, I can try the various models I have downloaded with it.

**Comment by Blaizzy** [comment]
@jrp2014 I can't replicate your issue. Could you share your env dependencies 

## Inference ✅
<img width="1485" alt="Screenshot 2024-12-22 at 5 58 19 PM" src="https://github.com/user-attachments/assets/e45dd35d-1f5d-4333-86bc-c04d772fe1fe" />

## Dependecies
<img width="686" alt="Screenshot 2024-12-22 at 5 59 14 PM" src="https://github.com/user-attachments/assets/390970e5-9bfa-47b4-8083-ca2991eb8c52" />

**Comment by jrp2014** [comment]
Here you go:

```
mlx                       0.21.1.dev20241220+0308e9af7
mlx-lm                    0.20.4
mlx-vlm                   0.1.4
mlx-whisper               0.4.1

transformers              4.47.1
```
Looks like I have a later mlx.

(I have no sentence-transformers or fastmlx)

**Comment by Blaizzy** [comment]
I upgraded to v0.21.1 and it works fine :)

Please uninstall the dev version and install the official last release of mlx and mlx-vlm from pypi.

```
pip install -U mlx mlx-vlm
```

![image](https://github.com/user-attachments/assets/6e14d12f-7e15-4150-b59c-5ce7a64b9d74)

**Comment by Blaizzy** [comment]
Hey @jrp2014 

Any updates here?

**Comment by jrp2014** [comment]
```
python -m mlx_vlm.generate --model mlx-community/Qwen2-VL-7B-Instruct-8bit --max-tokens 100 --temp 0.0
Fetching 12 files: 100%|█████████████████████████████████████████████████████████████| 12/12 [00:00<00:00, 19831.22it/s]
==========
Image: [] 

Prompt: <|im_start|>system
You are a helpful assistant.<|im_end|>
<|im_start|>user
What are these?<|im_end|>
<|im_start|>assistant

I'm sorry, but I'm not sure what you are referring to. Could you please provide more context or information about what you are asking about?
==========
Prompt: 23 tokens, 157.865 tokens-per-sec
Generation: 31 tokens, 61.341 tokens-per-sec
Peak memory: 8.849 GB
```

**Comment by Blaizzy** [comment]
So it's solved ✅

Please note that there is no image by default.
