### ISSUE TITLE
Error running mlx-community/Qwen2-VL-7B-4bit

### ISSUE THREAD

**Issue by jpschreiter** [Blaizzy/mlx-vlm#71]
Hi, 

found you're repository and tried to run qwen2-vl with the following code: 

```
import mlx.core as mx
from mlx_vlm import load, generate


model_path = "mlx-community/Qwen2-VL-7B-4bit"

model, processor = load(model_path)

prompt = processor.tokenizer.apply_chat_template(
    [{"role": "user", "content": f"<image>\nWhat are these?"}],
    tokenize=False,
    add_generation_prompt=True,
)

output = generate(model, processor, "http://images.cocodataset.org/val2017/000000039769.jpg", prompt, verbose=False)

print(output)
```

Getting following Error: 

```
Traceback (most recent call last):
  File "", line 16, in <module>
    output = generate(model, processor, "http://images.cocodataset.org/val2017/000000039769.jpg", prompt, verbose=False)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mlx_vlm/utils.py", line 959, in generate
    for (token, prob), n in zip(
  File "/mlx_vlm/utils.py", line 841, in generate_step
    logits = model(input_ids, pixel_values, cache=cache, mask=mask, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mlx_vlm/models/qwen2_vl/qwen2_vl.py", line 94, in __call__
    input_embddings = self.get_input_embeddings(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mlx_vlm/models/qwen2_vl/qwen2_vl.py", line 65, in get_input_embeddings
    final_inputs_embeds = self._merge_input_ids_with_image_features(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mlx_vlm/models/qwen2_vl/qwen2_vl.py", line 78, in _merge_input_ids_with_image_features
    inputs_embeds[image_positions] = image_features
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
ValueError: shape mismatch: value array of shape (391,3584) could not be broadcast to indexing result of shape (0,3584)
```

Anyone an idea how to resolve this issue?

Thanks.

**Comment by cparish312** [comment]
Also getting this issue. Seems like it's a problem with all `Qwen2-VL`. Also @Blaizzy you're the goat

**Comment by Blaizzy** [comment]
Ohh wait I know what the issue is. 

You are using the wrong image tokens

**Comment by Blaizzy** [comment]
Here is the proper format: 

```python
import mlx.core as mx
from mlx_vlm import load, generate


model_path = "mlx-community/Qwen2-VL-7B-4bit"

model, processor = load(model_path)

messages = [{
            "role": role,
            "content": [
                {"type": "text", "text": "What are these?"},
                {"type": "image"}
            ],
        }]
prompt = processor.tokenizer.apply_chat_template(
    messages,
    tokenize=False,
    add_generation_prompt=True,
)

output = generate(model, processor, "http://images.cocodataset.org/val2017/000000039769.jpg", prompt, verbose=False)

print(output)
```

**Comment by Blaizzy** [comment]
Thanks @cparish312!

**Comment by cparish312** [comment]
Yup works thanks!

**Comment by Blaizzy** [comment]
Happy to hear that 🙌🏽

My pleasure!

**Comment by jpschreiter** [comment]
Thanks, works great 👍
