### ISSUE TITLE
Error running mlx-community/pixtral-12b-4bit

### ISSUE THREAD

**Issue by jpschreiter** [Blaizzy/mlx-vlm#73]
Hi, 

using this code trying to run "mlx-community/pixtral-12b-4bit" model:

```
import mlx.core as mx
from mlx_vlm import load, generate

model_path = "mlx-community/pixtral-12b-4bit"

model, processor = load(model_path)

prompt = processor.tokenizer.apply_chat_template(
    [{"role": "user", "content": f"<image>\nWhat are these?"}],
    tokenize=False,
    add_generation_prompt=True,
)

pic = "xxx.png"

output = generate(model, processor, pic, prompt, verbose=False)

print(output)
```

Getting following error: 

```
Traceback (most recent call last):
  File "/pixtral.py", line 8, in <module>
    model, processor = load(model_path)
                       ^^^^^^^^^^^^^^^^
  File "/mlx_vlm/utils.py", line 249, in load
    model = load_model(model_path, lazy)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mlx_vlm/utils.py", line 215, in load_model
    model.load_weights(list(weights.items()))
  File "/mlx/nn/layers/base.py", line 178, in load_weights
    raise ValueError(f"Received parameters not in model: {extras}.")
ValueError: Received parameters not in model: vision_tower.vision_model.vision_model.transformer.layers.16.feed_forward.down_proj.weight vision_tower.vision_model.vision_model.transformer.layers.12.attention.q_proj.biases vision_tower.vision_model.vision_model.transformer.layers.22.attention.k_proj.scales vision_tower.vision_model.vision_model.transformer.layers.19.attention.v_proj.weight 
....
```

Anyone a solution? 

Thanks.

**Comment by Blaizzy** [comment]
Yeah, you can download and quantise the source model. Those quantised models have a small bug I will fix later today.

https://huggingface.co/mistral-community/pixtral-12b/tree/main
